spring:
  application:
    name: click-consumer

server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: click-aggregator
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true

logging:
  level:
    com.example.consumer: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN