spring:
  application:
    name: click-producer

server:
  port: 8081

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema:
        registry:
          url: http://localhost:8081
      enable:
        idempotence: true
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
      retries: 2147483647
      acks: all

logging:
  level:
    com.example.producer: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN